logging:
  level:
    com.serengeti.hyu.backend: DEBUG
spring:
  profiles:
    include: secret
  output:
    ansi:
      enabled: always
  config:
    import: classpath:application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hyu-db.cb66e4s0uqrs.ap-northeast-2.rds.amazonaws.com:3306/hyu_db
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update