name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: hyu-backend-bucket
  CODE_DEPLOY_APPLICATION_NAME: hyu-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: hyu-codedploy-deployment-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash
        
      - name: Make application-secret.yml
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.APPLICATION_SECRET }}" > ./application-secret.yml
        shell: bash
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean build -x test
        
      - name: Make zip file
        run: |
          mkdir deploy
          cp ./build/libs/*.jar ./deploy/
          zip -r -qq -j ./hyu-server-build.zip ./deploy
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Run MySQL container
        run: |
          docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=dongdukhyu \
            -e MYSQL_DATABASE=hyu_db \
            -e MYSQL_USER=hyu_admin \
            -e MYSQL_PASSWORD=dongdukhyu \
            -p 3306:3306 -d mysql:8
    
      - name: Upload to AWS S3
        run:  |
          aws deploy push \
            --application-name hyu-deploy \
            --ignore-hidden-files \
            --s3-location s3://hyu-backend-bucket/hyu-server-build.zip \
            --source .
          
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name hyu-deploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name hyu-codedploy-deployment-group \
            --s3-location bucket=$S3_BUCKET_NAME,key=hyu-server-build.zip,bundleType=zip
